name = "alsok-interview-system"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# デフォルト環境変数
[vars]
DEFAULT_TZ = "Asia/Tokyo"

# 本番環境設定
[env.production]
name = "alsok-interview-system"
vars = { DEFAULT_TZ = "Asia/Tokyo" }

# プレビュー環境設定（PR用）
[env.preview]
name = "alsok-interview-system-preview"
vars = { DEFAULT_TZ = "Asia/Tokyo" }

# 開発環境設定
[env.dev]
name = "alsok-interview-system-dev"
vars = { DEFAULT_TZ = "Asia/Tokyo", DEBUG_MODE = "true" }

# カスタムドメイン設定例
# [[routes]]
# pattern = "api.alsok-interview.com/*"
# zone_name = "alsok-interview.com"

# 本番環境の環境変数はGitHub Secretsで管理:
# - CLOUDFLARE_API_TOKEN
# - CLOUDFLARE_ACCOUNT_ID
# - GAS_WEBAPP_URL
# - GAS_AUTH_TOKEN  
# - TWILIO_ACCOUNT_SID
# - TWILIO_AUTH_TOKEN
# - TWILIO_MESSAGING_SERVICE_SID
# - ALLOWED_ORIGIN